### ISSUE TITLE
count_codons tries counting '---'

### ISSUE THREAD

**Issue by mendessoares** [biologyguy/BuddySuite#45] opened 2016-06-03 19:32 UTC
If the sequences in the file are not clean, warnings will be returned for things such as '---', '-A-', etc. (Warning: Codon '---' is invalid. Codon will be skipped.) It would be useful to have an option to clean the sequences.

**Comment by biologyguy** [comment] 2016-06-04 15:48
@j9chan is on this. There are several things that can be done with the count_codons function to improve readability and performance. She's already made some progress on the OP request by including a call to clean_seq(), although it causes a test to fail. 
Jennifer, I've looked closer at that failing test, and it's doing it's job of pointing out an issue we were overlooking. There's an extra piece of code in the count_codons() function that is specifically printing those warning messages to stderr, and it was intended to highlight characters in the sequence that are outside of the ambiguous alphabet (i.e., can't be classified properly as a codon). It's obviously also catching gap chars, which is not meaningful from a user's perspective. So we need to retain the ability to warn on weird letter characters but skip gaps. I recommend we use the replace_subsequence() function instead of clean_seqs(). Passing in the regular expression "[-.]" should clean up the gaps and leave everything else intact. 
Can you also remove all the seq.upper() calls in the loops? The entire sequence can be converted to upper before the codons are iteratively stripped off for counting.

**Comment by biologyguy** [comment] 2016-06-04 19:16
Possible pitfall Jennifer: Make sure you do a merge from remote (my fork) before doing anything further. We just made a significant structural change to the directory tree, and (I think) it'll be easier to merge your pull request if your repo is up to date.

**Comment by j9chan** [comment] 2016-06-15 03:31
Hey Steve, I made similar changes to https://github.com/j9chan/BuddySuite/blob/count_codons_fix/buddysuite/SeqBuddy.py using your suggestions. I noticed that the tests were moved into a deprecated folder and for some reason, I'm having some difficulties running them. I'll check back on the problem tomorrow. Thanks for the explanation ^! :)

**Comment by biologyguy** [comment] 2016-06-17 22:51
Hi Jen,
Ya, we're transitioning to a different test structure, so all of the old test files are being stored in the deprecated folder for now. They should still run though. If not, let's not fight it. I'll get the relevant SeqBuddy file set up in the new tests directory and put move the current state of test_count_codons over. Should be able to get that done soon (at a conference right now, so it'll depend on how much social stuff cuts into my downtime.)

**Comment by biologyguy** [comment] 2016-07-01 18:20
Resolved with commit 01c6363e208976272388cadf124d49f2c7acb285

**Closed by biologyguy** 2016-07-01 18:20 UTC
